create database customer_behavior;
show databases;
show tables;
select * from customer limit 10;
desc customer;
ALTER TABLE customer RENAME COLUMN `purchase_amount_(usd)` TO purchase_amount;
-- total revenue generated by male and female
select gender , SUM(purchase_amount) as total_revenue from customer group by gender;

-- which customer used a discount but still spent more than avg purchase amount
select customer_id , purchase_amount from customer where discount_applied  = 'yes' and purchase_amount>= (select AVG(purchase_amount) from customer);

-- If using:
--  Aggregate (AVG, SUM, MAX)
-- 👉 Usually need GROUP BY

-- which are the top 5 products with the highest average rating 
select item_purchased ,round(avg(review_rating),3) as average_rating from customer group by  item_purchased order by average_rating desc limit 5;

-- compare the average purchase amount between standard and express shipping
select shipping_type, AVG(purchase_amount) from customer where shipping_type in ('standard','express') group by shipping_type;

-- compare average spend and total revenue between subscribera and non -subscribers
select subscription_status, count(customer_id) as Total_customer, avg(purchase_amount) as avg_spend , SUM(purchase_amount) as total_revenue from customer group by subscription_status ;

-- which 5 product have the highest percentage of purchases with discount applied

select item_purchased ,(count(case when discount_applied = 'yes' then 1 end ) /count(*) )*100 as Perchases from customer  group by item_purchased order by Perchases desc  limit 5;

-- Segment customers into new,Returning, and loyal based on their total number of previous purchases, and show the count of each segment

select 
       case
            when previous_purchases  = 1 then 'New'
            when previous_purchases between 1 and 10 then 'Returning'
            else 'Loyal'
		end as 'Customer_Segment',
        count(*) as customer_count
        from customer
        group by customer_segment;

-- what are the top 3 most purchased product with in each category


-- it will give only 3 but we want for each category
SELECT category, item_purchased, COUNT(*) AS purchase_count
FROM customer
GROUP BY category, item_purchased                  
ORDER BY category, purchase_count DESC limit 3;
-- corrected version is :

SELECT *
FROM (
    SELECT category,
           item_purchased,
           COUNT(*) AS purchase_count,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(*) DESC
           ) rn
    FROM customer
    GROUP BY category, item_purchased
) as ranked
WHERE rn <= 3;

-- are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select subscription_status, Count(previous_purchases) as repeat_buyers from customer where previous_purchases>5 group by subscription_status;

-- what is the revenue contributions of each age group ?

select age,sum(purchase_amount) as revenue from customer group by age order by revenue desc;

select 
       case
		  when age between 15 and 24 then 'young adult'
          when age between 25 and 40 then 'adult'
          when age between 41 and 60 then 'middle-aged'
          else 'senior'
          end as age_group,
          sum(purchase_amount) as total_revenue
          from customer
          group by age_group
          order by total_revenue desc;
